"""empty table popilation

Revision ID: 3694c55adf2b
Revises: 
Create Date: 2025-09-07 11:20:59.975597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3694c55adf2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.String(length=299), nullable=False),
    sa.Column('displayable_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('profile_pic_object_name', sa.String(length=299), nullable=False),
    sa.Column('country', sa.String(length=299), nullable=False),
    sa.Column('timeRegistered', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('isAdmin', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('link',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.String(length=299), nullable=False),
    sa.Column('old_link', sa.String(length=299), nullable=False),
    sa.Column('new_link', sa.String(length=299), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('timeRegistered', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('click_count', sa.Integer(), server_default=sa.text("'0'"), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.user_id'], name='link_ibfk_1'),
    sa.PrimaryKeyConstraint('link_id')
    )
    op.create_index('creator_id', 'link', ['creator_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('creator_id', table_name='link')
    op.drop_table('link')
    op.drop_table('user')
    # ### end Alembic commands ###
