# Nginx server (added later), redis, db (added later)



services:
  nginx:
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/app/dist:/usr/share/nginx/html:ro
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_started
      backend:
        condition: service_started
      